Release of 2.3.7

diff --git a/nsdc.sh.in b/nsdc.sh.in
--- a/nsdc.sh.in
+++ b/nsdc.sh.in
@@ -8,109 +8,26 @@
 #
 #
 
-# configuration file default
-configfile="@nsdconfigfile@"
+# Optional configuration file for nsdc
+configfile="@configfile@"
 
-# The directory where NSD binaries reside
+#
+# Default values in absense of ${configfile} (Usually ``/etc/nsd/nsdc.conf'')
+#
+prefix="@prefix@"
+exec_prefix="@exec_prefix@"
+
 sbindir="@sbindir@"
-
-# how verbose is zonec run. Specificy Nothing (empty string), -v or -vv.
-ZONEC_VERBOSE=-v
-
-#
-# You sure heard this many times before: NO USER SERVICEABLE PARTS BELOW
-#
-
-# see if user selects a different config file, with -c <filename>
-if test "x$1" = "x-c"; then
-	shift
-	if [ -e $1 ]; then
-		configfile=$1
-		shift
-	else
-		echo "`basename $0`: Config file "$1" does not exist."
-		exit 1
-	fi
-fi
-
-# locate nsd-checkconf : in sbindir, PATH, nsdc_dir or .
-nsd_checkconf=""
-if [ -e ${sbindir}/nsd-checkconf ]; then
-	nsd_checkconf=${sbindir}/nsd-checkconf
-else
-	if which nsd-checkconf >/dev/null 2>&1 ; then
-		if which nsd-checkconf 2>&1 | grep "^[Nn]o " >/dev/null; then
-			nsd_checkconf=""
-		else
-			nsd_checkconf=`which nsd-checkconf`
-		fi
-	fi
-	if [ -z "${nsd_checkconf}" -a -e `dirname $0`/nsd-checkconf ]; then
-		nsd_checkconf=`dirname $0`/nsd-checkconf
-	fi
-	if [ -z "${nsd_checkconf}" -a -e ./nsd-checkconf ]; then
-		nsd_checkconf=./nsd-checkconf
-	fi
-	if [ -z "${nsd_checkconf}" ]; then
-		echo "`basename $0`: Could not find nsd programs" \
-			"in $sbindir, in PATH=$PATH, in cwd=`pwd`," \
-			"or in dir of nsdc=`dirname $0`"
-		exit 1
-	fi
-fi
-
-usage() {
-	echo "Usage: `basename $0` [-c configfile] {start|stop|reload|rebuild|restart|"
-	echo "				running|update|notify|patch}"
-	echo "options:"
-	echo "	-c configfile	Use specified configfile (default: @nsdconfigfile@)."
-	echo "commands:"
-	echo "	start		Start nsd server."
-	echo "	stop		Stop nsd server."
-	echo "	reload		Nsd server reloads database file."
-	echo "	rebuild		Compile database file from zone files."
-	echo "	restart		Stop the nsd server and start it again."
-	echo "	running		Prints message and exit nonzero if server not running."
-	echo "	update		Try to update all slave zones hosted on this server."
-	echo "	notify		Send notify messages to all secondary servers."
-	echo "	patch		Merge zone transfer changes back to zone files."
-}
-
-# check the config syntax before using it
-${nsd_checkconf} ${configfile}
-if test $? -ne 0 ; then
-	usage
-	exit 1
-fi
-
-# Read some settings from the config file.
-dbfile=`${nsd_checkconf} -o database ${configfile}`
-pidfile=`${nsd_checkconf} -o pidfile ${configfile}`
-difffile=`${nsd_checkconf} -o difffile ${configfile}`
-zonesdir=`${nsd_checkconf} -o zonesdir ${configfile}`
-lockfile="${dbfile}.lock"  # still needed
-sbindir=`dirname ${nsd_checkconf}`
-
-# move to zonesdir (if specified), and make absolute pathnames.
-if test -n "${zonesdir}"; then
-       zonesdir=`dirname ${zonesdir}/.`
-       if echo "${zonesdir}" | grep "^[^/]" >/dev/null; then
-               zonesdir=`pwd`/${zonesdir}
-       fi
-       if echo "${dbfile}" | grep "^[^/]" >/dev/null; then
-               dbfile=${zonesdir}/${dbfile}
-       fi
-       if echo "${pidfile}" | grep "^[^/]" >/dev/null; then
-               pidfile=${zonesdir}/${pidfile}
-       fi
-       if echo "${lockfile}" | grep "^[^/]" >/dev/null; then
-               lockfile=${zonesdir}/${lockfile}
-       fi
-       if echo "${difffile}" | grep "^[^/]" >/dev/null; then
-               difffile=${zonesdir}/${difffile}
-       fi
-fi
-
+zonesdir="@zonesdir@"
+flags=""
+dbfile="@dbfile@"
+zonesfile="@zonesfile@"
+keysdir="@configdir@/keys"
+notify="@sbindir@/nsd-notify"
+nsdxfer="@sbindir@/nsd-xfer"
+nsdxfer_flags=""
+pidfile="@pidfile@"
+lockfile="@dbfile@.lock"
 # for bash: -C or noclobber. For tcsh: noclobber. For bourne: -C.
 noclobber_set="set -C"
 # ugly check for tcsh
@@ -118,8 +35,18 @@ if echo @shell@ | grep tcsh >/dev/null; then
 	noclobber_set="set noclobber"
 fi
 
+ZONEC_VERBOSE=-v
+
 #
-# useful routines
+# Read in configuration file if any
+#
+if [ -f ${configfile} ]
+then
+	. ${configfile}
+fi
+
+#
+# You sure heard this many times before: NO USER SERVICEABLE PARTS BELOW
 #
 signal() {
 	if [ -s ${pidfile} ]
@@ -132,7 +59,7 @@ signal() {
 }
 
 lock() {
-        (umask 222; ${noclobber_set}; echo "database locked by PID: $$" >${lockfile}) ||
+        (umask 222; $noclobber_set; echo "database locked by PID: $$" >${lockfile}) ||
                 (cat ${lockfile} ; echo "aborting..." ; exit 1)
 	[ $? = 0 ] || exit 1
 }
@@ -141,168 +68,139 @@ unlock() {
 	rm -f ${lockfile}
 }
 
-do_start() {
-	if test -x ${sbindir}/nsd; then
-		${sbindir}/nsd -c ${configfile}
-		test $? = 0 || (echo "nsd startup failed."; exit 1)
-	else
-		echo "${sbindir}/nsd not an executable file, nsd startup failed."; exit 1
-	fi
-}
-
-do_stop() {
-	signal "TERM"
-}
-
-do_reload() {
-	signal "HUP"
-}
-
-# send_updates zone_name {ip_spec key_spec}
-send_updates() {
-	local zonename=$1
-	shift
-	# extract port number (if any) 
-	port=`${nsd_checkconf} -o port ${configfile}`
-	if test -n "${port}"; then
-		port="-p ${port}"
-	fi
-	update_sent="no"
-
-	while test $# -gt 0; do
-		ip_spec=$1
-		key_spec=$2
-		shift 2
-		# only if localhost is allowed.
-		# see if zone has 127.0.0.1 or ::1 as allowed.
-		if test Z${ip_spec} = "Z127.0.0.1" -o Z${ip_spec} = "Z::1"; then
-			secret=""
-			if test K${key_spec} != KNOKEY -a K${key_spec} != KBLOCKED; then
-				secret=`${nsd_checkconf} -s ${key_spec} ${configfile}`
-				secret="-y ${key_spec}:${secret}"
-			fi
-			if test K${key_spec} != KBLOCKED; then
-				#echo "${sbindir}/nsd-notify ${port} " \
-				#"-z ${zonename} ${ip_spec} # with ${key_spec}"
-				${sbindir}/nsd-notify ${port} ${secret} \
-				-z ${zonename} ${ip_spec} && update_sent="yes"
-			fi
-		fi
-	done
-	if test ${update_sent} = no; then
-		req_xfr=`${nsd_checkconf} -z "${zonename}" -o request-xfr ${configfile}`
-		if test -n "${req_xfr}"; then
-			# must be a slave zone (has request-xfr).
-			echo "`basename $0`: Could not send notify for slave zone ${zonename}: not configured (with allow-notify: 127.0.0.1 or ::1)"
-		fi
-	fi
-}
-
-# send_notify zone_name {ip_spec key_spec}
-send_notify() {
-	local zonename=$1
-	shift
-	while test $# -gt 0; do
-		ip_spec=$1
-		key_spec=$2
-		shift 2
-		secret=""
-		if test K${key_spec} != KNOKEY -a K${key_spec} != KBLOCKED; then
-			secret=`${nsd_checkconf} -s ${key_spec} ${configfile}`
-			secret="-y ${key_spec}:${secret}"
-		fi
-		if test K${key_spec} != KBLOCKED; then
-			port=""
-			ipaddr=${ip_spec}
-			if echo ${ip_spec} | grep @ >/dev/null; then
-				port="-p "`echo ${ip_spec} | sed -e 's/[^@]*@\([0-9]*\)/\1/'`
-				ipaddr=`echo ${ip_spec} | sed -e 's/\([^@]*\)@[0-9]*/\1/'`
-			fi
-			${sbindir}/nsd-notify ${port} ${secret} -z ${zonename} ${ipaddr}
-		fi
-	done
-}
-
-do_rebuild() {
-	lock && \
-	  ${sbindir}/zonec ${ZONEC_VERBOSE} -c ${configfile} -f ${dbfile}.$$ && \
-	  mv ${dbfile}.$$ ${dbfile}
-	result=$?
-	unlock
-	[ $result != 0 ] && echo "${dbfile} is unmodified"
-	rm -f ${dbfile}.$$
-	return ${result}
-}
-
 case "$1" in
 start)
-	do_start
+	[ -x ${sbindir}/nsd ] && ${sbindir}/nsd -f ${dbfile} -P ${pidfile} ${flags}
+	$0 notify
 	;;
 stop)
-	do_stop
+	signal "TERM"
 	;;
 stats)
 	signal "USR1"
 	;;
 reload)
-	do_reload
+	signal "HUP"
+	$0 notify
 	;;
 running)
 	signal "0"
 	;;
-patch)
-        # patch queue clearen
-	if test -s ${difffile}; then
-		#${sbindir}/nsd-patch -c ${configfile} -x ${difffile} -l #debug
-		#echo ${sbindir}/nsd-patch -c ${configfile} -x ${difffile}
-		if lock && \
-		  mv ${difffile} ${difffile}.$$ && \
-		  ${sbindir}/nsd-patch -c ${configfile} -x ${difffile}.$$ \
-		  && rm -f ${difffile}.$$ && unlock && do_rebuild; then
-			do_reload
-		else
-			unlock
-			# try to move back the transfer data
-			if [ -e ${difffile}.$$ -a ! -e ${difffile} ]; then
-				mv ${difffile}.$$ ${difffile}
-			fi
-			echo "`basename $0`: patch failed."
-		fi
-	else
-		echo "`basename $0`: no patch necessary."
-	fi
-        ;;
 rebuild)
-	do_rebuild
+	${sbindir}/zonec ${ZONEC_VERBOSE} -d ${zonesdir} -f ${dbfile}.$$ ${zonesfile} && mv ${dbfile}.$$ ${dbfile}
+	result=$?
+	[ $result != 0 ] && echo "${dbfile} is unmodified"
+	rm -f ${dbfile}.$$
+	exit ${result}
 	;;
 update)
-        # send notifies to localhost for all zones that allow it
-	echo "Sending notify to localhost to update secondary zones..."
-	if [ -s ${pidfile} ]; then
-		zoneslist=`${nsd_checkconf} -o zones ${configfile}`
-		for zonename in ${zoneslist}; do
-			notify_allow=`${nsd_checkconf} -z "${zonename}" -o allow-notify ${configfile}`
-			send_updates ${zonename} ${notify_allow}
-		done
-	else
-		echo "nsd is not running"
+	#
+	if [ ! -x "${nsdxfer}" ]
+	then
+		echo "named-xfer program is not available, aborting..."
+		exit 1
 	fi
+
+	lock
+
+	# read the nsd.zones file
+	while read zonekw zone file masterskw masters
+	do	
+		if [ "X$zonekw" = "Xzone" -a "X$masterskw" = "Xmasters" ]
+		then
+			# now get the serial number
+			serial_opt=''
+			if [ -e ${zonesdir}/$file ]; then
+				serial=`awk '/.*IN[ \t]+SOA.*\($/ { getline; print $1; exit }' ${zonesdir}/$file`
+				serial_opt="-s $serial"
+			fi
+
+			# take care of tsig info file if any
+			# See bug #91 - move to ${zone} but be backward
+			# compatible
+			unset tsiginfoarg
+			if [ -f "${keysdir}/${masters}.tsiginfo" ]
+			then
+				ln "${keysdir}/${masters}.tsiginfo" "${keysdir}/${masters}.tsiginfo.$$"
+				tsiginfoarg="-T ${keysdir}/${masters}.tsiginfo.$$"
+			else 
+				if [ -f "${keysdir}/${zone}.tsiginfo" ]
+				then
+					# the new way of doing things
+					ln "${keysdir}/${zone}.tsiginfo" "${keysdir}/${zone}.tsiginfo.$$"
+					tsiginfoarg="-T ${keysdir}/${zone}.tsiginfo.$$"
+				fi
+			fi
+
+			# AXFR to a temp file $file.axfr
+			$nsdxfer $nsdxfer_flags -z $zone -f ${zonesdir}/$file.axfr ${tsiginfoarg} $serial_opt $masters
+			if [ $? -eq 1 ]
+			then
+				if [ -f ${zonesdir}/$file.axfr ]
+				then
+					# axfr succeeded
+					# test compile the zone to see what happens
+					${sbindir}/zonec -o ${zone} -f ${zonesdir}/$file.axfr.db - < ${zonesdir}/$file.axfr 2>/dev/null
+					if [ $? -eq 1 ]
+					then
+						echo "Warning: AXFR of $zone did not compile"
+						rm -f ${zonesdir}/$file.axfr
+					else
+						# we succeed
+						mv -f ${zonesdir}/$file.axfr ${zonesdir}/$file
+					fi
+					rm -f ${zonesdir}/$file.axfr.db
+				else
+					echo "Warning: AXFR for $zone failed"
+				fi
+			fi
+
+			# Do we need to rebuild the database?
+			if [ ${zonesdir}/$file -nt ${dbfile} ]
+			then
+				echo "zone $zone needs rebuilding..."
+				rebuild="yes"
+				export $rebuild
+			fi
+
+			# clean up
+			rm -f -- "${keysdir}"/*.tsiginfo.*
+		fi
+	done < $zonesfile
+
+	# Wait for everybody to terminate
+	wait
+
+	# Rebuild and reload?
+	if [ ! -f ${dbfile} -o "x$rebuild" = "xyes" ]
+	then
+		echo "rebuilding the database...."
+		sh $0 rebuild && sh $0 reload
+	fi
+
+	unlock
 	;;
 notify)
-	# send notifies to all slaves
-	echo "Sending notify to slave servers..."
-	zoneslist=`${nsd_checkconf} -o zones ${configfile}`
-	for zonename in ${zoneslist}; do
-		notify=`${nsd_checkconf} -z "${zonename}" -o notify ${configfile}`
-		send_notify ${zonename} $notify
-	done
+	if [ ! -x "${notify}" ]
+	then
+		echo "nsd-notify was not installed on this system"
+		exit 1
+	fi
+
+	# read the nsd.zones file
+	while read zonekw zone file notifykw slaves
+	do	
+		if [ "X$zonekw" = "Xzone" -a "X$notifykw" = "Xnotify" ]
+		then
+			$notify -z "$zone" $slaves
+		fi
+	done < $zonesfile
 	;;
 restart)
-	do_stop && sleep 1
-	do_start
+	sh $0 stop && sleep 1 && sh $0 start
 	;;
 *)
-	usage
+	echo "Usage: `basename $0` {start|stop|reload|rebuild|restart|running|update|notify}" >&2
 	;;
 esac
 
